language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
cache:
  directories:
    - vendor
script:
  - if [[ -f "vendor/.cache" ]]; then mv vendor/.cache src/.cache; fi
  - composer install
  - vendor/bin/nose
  - if [[ -f "src/.cache" ]]; then mv src/.cache vendor/.cache; fi
