language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
arch:
  - amd64
  - arm64
cache:
  directories:
    - vendor
script:
  - if [[ -f "vendor/.json_cache" ]]; then mv vendor/.json_cache src/.json_cache; fi
  - composer install
  - vendor/bin/nose
  - if [[ -f "src/.json_cache" ]]; then mv src/.json_cache vendor/.json_cache; fi
